using System;

namespace Seagull.SourceGenerators;

/// <summary>
/// Simple constants values
/// </summary>
public class Constants
{
    /// <summary>
    /// Current version
    /// </summary>
    public static string Version = "1.0.0";
    
    /// <summary>
    /// Header to place in all generated source code 
    /// </summary>
    public static string CodeHeader = $@"// ------------------------------------------------------------------------------
// <autogenerated>
//      This code has been generated using Oluso SourceGenerators v{Version}.
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated. 
// </autogenerated>
// ------------------------------------------------------------------------------"
        .Replace("\r\n", "\n");
}
